services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5050:5050"
volumes:
  pgdata: