services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: